name = "Epic_Mod_Pack"
author = "Galaxy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "809c2373f40c24a548146550e04c380040d5e501522ac4f3bbdd2f612d2a7d71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"
